// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoWeb.Models;

#nullable disable

namespace ProyectoWeb.Migrations
{
    [DbContext(typeof(ProyectoWebContext))]
    [Migration("20231004070148_Modelos")]
    partial class Modelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoWeb.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula_clientes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoWeb.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salario_colaborador")
                        .HasColumnType("real");

                    b.Property<string>("Telefono_colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("ProyectoWeb.Models.Roles", b =>
                {
                    b.Property<int>("Id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_rol"));

                    b.Property<string>("Descripcion_rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3213E83F6272EB99");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
